theme: minima
title: "A blog for cybersecurity curious people"
author: Robb-Fr
description: "I write posts about the interesting information security stuff I find about"
show_excerpts: true
minima:
  skin: dark
